/// <reference path="chrome-api-vsdoc.js" />
/// <reference path="/app/js/jquery-2.0.3.min.js"/>
/// <reference path="jquery-2.1.4.min.map"/>
/// <reference path="/app/js/jquery.contextMenu.js" />
/// <reference path="../app/elements/crm-edit-page/crm-edit-page.js" />
/// <reference path="../app/elements/crm-app/crm-app.js" />
/// <reference path="../app/elements/default-link/default-link.js" />
/// <reference path="../app/elements/edit-crm/edit-crm.js" />
/// <reference path="../app/elements/edit-crm-item/edit-crm-item.js" />
/// <reference path="../app/elements/link-edit/link-edit.js" />
/// <reference path="../app/elements/paper-dropdown-menu/paper-dropdown-menu.js" />
/// <reference path="../app/elements/paper-toggle-option/paper-toggle-option.js" />
/// <reference path="../app/elements/script-edit/script-edit.js" />
/// <reference path="../app/elements/type-switcher/type-switcher.js" />
/// <reference path="../app/js/codemirror.js" />
/// <reference path="../app/js/jquery-ui.min.js" />
/// <reference path="../app/js/jquery.color-2.1.2.min.js" />
/// <reference path="../app/js/jquery.requestAnimationFrame.min.js" />